fix scalereport.conda.yml
- pip is no longer required
- pip install was throwing error:
```[bash]
      Installing pip dependencies: - Pip subprocess error:
        error: subprocess-exited-with-error
        
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [5 lines of output]
            /tmp/pip-install-3575vleg/lxml_b01e9f838595457a9689fe09f06dcec0/setup.py:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
              import pkg_resources
            Building lxml version 4.9.4.
            Building without Cython.
            Error: Please make sure the libxml2 and libxslt development packages are installed.
            [end of output]
        
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
```